Ptd-lab04.ASP/Models/Customer.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Ptd_lab04.ASP.Models
{
    public class PtdCustomer
    {
        public string CustomerId { get; set; }
        public string FullName { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public decimal Balance { get; set; }
    }
}

Ptd-lab04.ASP/Controllers/CustomerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Ptd_lab04.ASP.Controllers
{
    public class CustomerController : Controller
    {
        // GET: /Customer/CustomerDetail (action returns detailed information of a customer for the CustomerDetail view)
        public ActionResult CustomerDetail()
        {
            // Create a Customer object
            Customer cus = new PtdCustomer()
            {
                CustomerId = "KH001",
                FullName = "Pham Thanh Dat",
                Address = "Nam Dinh",
                Email = "thanhdat160924@gmail.com",
                Phone = "0378.630.848",
                Balance = 15200000
            };

            // Passing data to the view using a model
            return View(cus);
        }

        // GET: /Customer/CustomerList (action returns a list of customers for the CustomerList view)
        public ActionResult CustomerList()
        {
            // Create a list of customers
            List<PtdCustomer> listcustomer = new List<PtdCustomer>()
            {
                new PtdCustomer()
                {
                    CustomerId = "KH001",
                    FullName = "Pham Thanh Dat",
                    Address = "Nam Dinh",
                    Email = "thanhdat160924@gmail.com",
                    Phone = "0378.630.848",
                    Balance = 15200000
                },
                new PtdCustomer()
                {
                    CustomerId = "KH002",
                    FullName = "Đỗ Thị Cúc",
                    Address = "Hà Nội",
                    Email = "cucdt@gmail.com",
                    Phone = "0986.767.444",
                    Balance = 2200000
                },
                new PtdCustomer()
                {
                    CustomerId = "KH003",
                    FullName = "Nguyễn Tuấn Thắng",
                    Address = "Nam Định",
                    Email = "thangnt@gmail.com",
                    Phone = "0924.656.542",
                    Balance = 1200000
                },
                new PtdCustomer()
                {
                    CustomerId = "KH004",
                    FullName = "Lê Ngọc Hải",
                    Address = "Hà Nội",
                    Email = "hailn@gmail.com",
                    Phone = "0996.555.267",
                    Balance = 6200000
                }
            };

            // Passing data to the view using ViewBag
            ViewBag.listcustomer = listcustomer;
            return View();
        }
    }
}

Ptd-lab04.ASP/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Ptd_lab04.ASP.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Ptd-lab04.ASP/Views/Customer/CustomerDetail.cshtml
@{
    ViewBag.Title = "Chi tiết khách hàng";
    //lấy dữ liệu truyền qua đối tượng theo cách 2
    //var customer = Model as Ptd_lab04.ASP.Models.Customer;
}

<h2>Chi tiết khách hàng lấy theo cách 1</h2>
<p>Mã số: @Model.CustomerId </p>
<p>Họ và tên: @Model.FullName </p>
<p>Địa chỉ: @Model.Address </p>
<p>Điện thoại: @Model.Phone </p>
<p>Email: @Model.Email </p>
<p>Số tiền dư: @Model.Balance </p>

Ptd-lab04.ASP/Views/Customer/CustomerList.cshtml
@{ViewBag.Title = "Danh sách khách hàng";
    //lấy danh sách khách hàng và convert data
    var listcustomer = ViewBag.listcustomer as List<Ptd_lab04.ASP.Models.PtdCustomer>;
}
<h2>Danh sách khách hàng</h2>
<table class="table-bordered">
    <thead>
        <tr>
            <th>Mã KH</th>
            <th>Họ và tên</th>
            <th>Địa chỉ</th>
            <th>Email</th>
            <th>Điện thoại</th>
            <th>Số dư</th>
        </tr>
    </thead>
    <tbody>
        @*Hiển thị danh sách khách hàng*@
        @foreach (var c in listcustomer)
        {
            <tr>
                <td>@c.CustomerId</td>
                <td>@c.FullName</td>
                <td>@c.Address</td>
                <td>@c.Email</td>
                <td>@c.Phone</td>
                <td>@c.Balance</td>
            </tr>
        }
    </tbody>
</table>

Ptd-lab04.ASP/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Ptd-lab04.ASP/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Ptd-lab04.ASP/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

Ptd-lab04.ASP/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>
                        @Html.ActionLink("Khách hàng", "CustomerDetail","Customer")
                </li>
                <li>
                    @Html.ActionLink("Danh sách khách hàng", "CustomerList","Customer")
                </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>